# Generated by Django 6.1.1 on 2026-10-06 12:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstapp", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Classroom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("key", models.CharField(max_length=50, unique=True)),
                (
                    "students",
                    models.ManyToManyField(
                        blank=True,
                        related_name="student_classrooms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "teachers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="teaching_classrooms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
