# Generated by Django 6.1.1 on 2026-10-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstapp", "0003_assignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="attachment",
            field=models.FileField(
                blank=True, null=True, upload_to="assignment_attachments/"
            ),
        ),
    ]
